on:
  push:
    branches: ["main"]
  workflow_dispatch:
  gollum:

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vanjac/chroma-zone-publish@main
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          wiki: docs
          download: true
